### ISSUE TITLE
Each message is being compiled on every request

### ISSUE THREAD

**Issue by brakon** [krakenjs/dust-message-helper#3]
On line 45 of the index.js

```
var tmpl = dust.cache[cacheKey] || dust.loadSource(dust.compile(value, cacheKey));
```

There is an effort to use dust.cache to prevent compiling the message key every single time, BUT this cache is emptied on every single request which means you are not going to benefit from caching unless you use the same cache key in the same page multiple times.

According to our load testing this is causing some CPU usage increase.

Why not have a application level caching rather than a request one?

Am I missing something?

**Comment by aredridel** [comment]
How is the cache being emptied? It should use dust's cache as is, if you've configured dust with caching enabled.

**Comment by brakon** [comment]
Cache is being disabled in EngineMunger v0.2.8

```
// Disabling cache
// since we add our own caching layer below. (Clone it first so we don't muck with the original object.)
settings.cache = false;
```

So when the cache variable is false, Adaro v0.1.8 resets the cache:

```
if (!config.cache) {
  console.log('Cleaning cach in adaro because' + config.cache);
  dust.cache = {};
}
```

We are using Kraken v1.0.5

**Comment by aredridel** [comment]
Ah! You'd want to use this with `makara@^2.0.0` and `engine-munger@^1.0.0`. The cache behavior is better there, and more carefully controlled.
